import {ClaudeIOEvent} from "../../core/events/claude-io-event.type.js";

export const data = {
    type: "system",
    subtype: "init",
    cwd: "/Users/ben/khan/perseus",
    session_id: "4bef8ebb-305b-446b-8e8a-dd79f3020e5e",
    tools: [
        "Task",
        "TaskOutput",
        "Bash",
        "Glob",
        "Grep",
        "ExitPlanMode",
        "Read",
        "Edit",
        "Write",
        "NotebookEdit",
        "WebFetch",
        "TodoWrite",
        "WebSearch",
        "TaskStop",
        "AskUserQuestion",
        "Skill",
        "EnterPlanMode",
        "EnterWorktree",
        "ToolSearch",
    ],
    mcp_servers: [],
    model: "claude-sonnet-4-6",
    permissionMode: "default",
    slash_commands: [
        "keybindings-help",
        "debug",
        "claude-developer-platform",
        "compact",
        "context",
        "cost",
        "init",
        "pr-comments",
        "release-notes",
        "review",
        "security-review",
        "insights",
    ],
    apiKeySource: "none",
    claude_code_version: "2.1.49",
    output_style: "default",
    agents: ["Bash", "general-purpose", "statusline-setup", "Explore", "Plan"],
    skills: ["keybindings-help", "debug", "claude-developer-platform"],
    plugins: [],
    uuid: "73f69673-84f0-4454-901b-bf5b906f836f",
    fast_mode_state: "off",
};

export const expected: ClaudeIOEvent[] = [];
